### ISSUE TITLE
Class '\Omnipay\PaymentSense\Gateway' not found'

### ISSUE THREAD

**Issue by tomchamp** [coatesap/omnipay-paymentsense#4]
Hello, hopefully some one is listening here. I've recently had a client who is insistent on using Payment sense, i've begun the process of introducing this into the app using this integration for Omnipay, but with little luck. 

If i choose any other payment gateway, stripe / paypal etc, they work perfect, otherwise I get an error i cannot work out. 

I similar issue has been reported here: https://groups.google.com/forum/#!topic/omnipay/Ji-YBZp7Sj0

The suggested resolution does not work. Could someone help?

**Comment by tomchamp** [comment]
Actually to test, I quickly changed over to another gateway, randomly picked... "Pagarme" and it works fine, i suspect its something to do with bad name spacing? or the Gateway.php file.

I'll continue to dig as this is something i'd like resolved to ease my integration with PaymentSense, they're documentation is horrible.

**Comment by coatesap** [comment]
Hi Tom, this is one of those Omnipay things which isn't very obvious, but I can see why it was done that way. 

When you create the instance of the driver, you need to specify the complete namespace and class name. This is because it is not one of the drivers maintained by the core Omnipay team, living under the main Omnipay namespace.

For example:
`$gateway = Omnipay::create('\Coatesap\PaymentSense\Gateway');`

I'll put this example on the readme page so it's there for anyone else who stumbles across this problem.

**Comment by tomchamp** [comment]
Ahh coatesap, that solved it. Thank you for your help.
